### PR TITLE
TP-963: Update Gigaspaces to 16.1.0 and Spring Framework to 5.3.7

### PR DESCRIPTION
**Pull request by ath0s**

### CODE REVIEW

**Review by Bjornelmers — APPROVED** [review]
Looks good!

**Comment by Bjornelmers** [comment]
I was looking at this PR: https://github.com/AvanzaBank/gs-test/pull/26 where an upgrade of Hamcrest to 2.2 is suggested and the upgrade instructions for hamcrest: http://hamcrest.org/JavaHamcrest/distributables#maven-upgrade-example.

What do you think about that? Do we need to declare hamcrest-library before other dependencies as suggested in the instructions?

**Comment by pativa** [comment]
Looks good!

**Review by pativa — APPROVED** [review]

**Comment by ath0s** [comment]
> I was looking at this PR: #26 where an upgrade of Hamcrest to 2.2 is suggested and the upgrade instructions for hamcrest: http://hamcrest.org/JavaHamcrest/distributables#maven-upgrade-example.
> 
> What do you think about that? Do we need to declare hamcrest-library before other dependencies as suggested in the instructions?

I think it is cleaner to exclude the transitive `hamcrest-core` dependency from junit, then adding the proper `hamcrest` dependency where needed. Otherwise you end up with the shim `hamcrest-core` on the classpath. 
For this project, hamcrest is only used in the tests so I added it with test scope. 

I should add that in general I agree that we should follow the suggested way to upgrade, but in this case I prefer to do it in the way described above for a cleaner classpath.

**Pull request merged**
